"""add os column to click_events

Revision ID: 75d661840dfd
Revises: c55f566e8e0a
Create Date: 2026-10-08 21:53:02.675283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d661840dfd'
down_revision: Union[str, Sequence[str], None] = 'c55f566e8e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('click_events', sa.Column('os', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('click_events', 'os')
    # ### end Alembic commands ###
